### ISSUE TITLE
spoa-mirror failing to properly forward a  Post when it encounters a header without a value

### ISSUE THREAD

**Issue by mark-k-english** [haproxytech/spoa-mirror#10]
Several indications that the message was properly processed exist but when I look at debugging output it shows all headers being processed when i eliminate the header with the missing value. In the output below the bad header is passphrase.

Does not work properly end to end example debugging:
                                                                         
[ 1][   72.999218]   <1> mirror[3] name='arg_hdrs' type=9:
<.content-length.249551.psp_qpassword.password.psp_instance.dev100023.psp_quser.qa/qa.psp_input_queue.psp.out.replicator.ivantest.passphrase..content-type.text/json.x-snc-integration-source 75157ea6db3644502f68c59705961924.user-agent.Jakarta Commons-HttpClient/3.1.host(us-east-2-pspprod-proxy2.perspectium.net..>
[ 1][   72.999224]   <1> str[0]: <content-length>
[ 1][   72.999242]   <1> str[1]: <249551>
[ 1][   72.999245]   <1> str[2]: <psp_qpassword> 
[ 1][   72.999252]   <1> str[3]: <password>
[ 1][   72.999255]   <1> str[4]: <psp_instance> 
[ 1][   72.999268]   <1> str[5]: <dev100023>
[ 1][   72.999273]   <1> str[6]: <psp_quser>
[ 1][   72.999280]   <1> str[7]: <qa/qa> 
[ 1][   72.999283]   <1> str[8]: <psp_input_queue>
[ 1][   72.999290]   <1> str[9]: <psp.out.replicator.ivantest> 
[ 1][   72.999293]   <1> str[10]: <passphrase> ** This is the header with no value!
[ 1][   72.999299]   <1> str[11]: <>            
                      
Does work properly:   
                      
[ 2][ 4031.637834]   <2> mirror[3] name='arg_hdrs' type=9: <>
<.content-length.249551.psp_qpassword.password.psp_instance.dev100023.psp_quser.qa/qa.psp_input_queue.psp.out.replicator.ivantest.passphrase.abc123.content-type.text/json.x-snc-integration-source 75157ea6db3644502f68c59705961924.user-agent.Jakarta Commons-HttpClient/3.1.host(us-east-2-pspprod-proxy2.abc.net..>
[ 2][ 4031.637840]   <2> str[0]: <content-length>
[ 2][ 4031.637859]   <2> str[1]: <249551> 
[ 2][ 4031.637862]   <2> str[2]: <psp_qpassword>
[ 2][ 4031.637871]   <2> str[3]: <password>
[ 2][ 4031.637874]   <2> str[4]: <psp_instance>
[ 2][ 4031.637883]   <2> str[5]: <dev100023>
[ 2][ 4031.637886]   <2> str[6]: <psp_quser>
[ 2][ 4031.637895]   <2> str[7]: <qa/qa>
[ 2][ 4031.637898]   <2> str[8]: <psp_input_queue>
[ 2][ 4031.637912]   <2> str[9]: <psp.out.replicator.ivantest>
[ 2][ 4031.637915]   <2> str[10]: <passphrase>
[ 2][ 4031.637925]   <2> str[11]: <abc123>
[ 2][ 4031.637927]   <2> str[12]: <content-type>
[ 2][ 4031.643749]   <2> str[13]: <text/json>
[ 2][ 4031.643772]   <2> str[14]: <x-snc-integration-source>
[ 2][ 4031.643854]   <2> str[15]: <75157ea6db3644502f68c59705961924>
[ 2][ 4031.643857]   <2> str[16]: <user-agent> 
[ 2][ 4031.643867]   <2> str[17]: <Jakarta Commons-HttpClient/3.1>
[ 2][ 4031.643870]   <2> str[18]: <host>
[ 2][ 4031.643879]   <2> str[19]: <us-east-2-pspprod-proxy2.abc.net>
[ 2][ 4031.643882]   <2> str[20]: <>

**Comment by zaga00** [comment]
Hello @mark-k-english,

what version of the program are you using?  Commit 69a52d9 fixes similar (or the same) bug.

There is something strange about displaying this issue because it lacks the content of individual lines. In the mail I received these lines are complete, they are not here.

**Comment by mark-k-english** [comment]
Hi,

Sorry about not making sure I was using the latest version before creating
an issue. The current version solves my problem, thanks much! ME

**Comment by zaga00** [comment]
No problem.  Thank you for reporting.
