### ISSUE TITLE
mirror http only (non-tls) if terminating tls on haproxy possible?

### ISSUE THREAD

**Issue by amsnek** [haproxytech/spoa-mirror#35]
Is it somehow possible to directly mirror traffic unencrypted if terminating on haproxy? (without construcing a loop that sends to a backend (that is a fronted) or similiar complex?

**Comment by zaga00** [comment]
Hello @amsnek,
if haproxy terminates ssl, unencrypted content is sent to the mirror.

**Comment by amsnek** [comment]
then I must have some error -> will retry. For me the Mirroring worked only if the Frontend is port 80/unencrypted -> with TLS + Termination, nothing was send to the port 80 (localhost) mirror -> I somehow assumed it was maybe because of encryption

**Comment by zaga00** [comment]
@amsnek, thanks for the debug output.

I think the problem is that in that case, instead of
`args arg_method=method arg_path=url arg_ver=req.ver arg_hdrs=req.hdrs_bin arg_body=req.body`
,
`args arg_method=method arg_path=path arg_ver=req.ver arg_hdrs=req.hdrs_bin arg_body=req.body`
 should be written in the file spoe.cfg

**Comment by amsnek** [comment]
Hello @zaga00 
I just realised that while "arg_path=path" works, it does not contain the full request (query etc). is there a way to provide the full path+arguments? (URI)? 
Should I open a feature request instead?

**Comment by zaga00** [comment]
Hello @amsnek,

I used `test/haproxy-mw.cfg` and `test/spoe.cfg` configurations for testing.

**Comment by amsnek** [comment]
Hello @zaga00 
Hmm, yes with "arg_path=url" it seems to work as expected ... I could have sworn that with "arg_path=url" it caused issues with the http scheme -> thanks. Will change arg_path=path" -> arg_path=url"
Closing the Issue, thanks :)

**Comment by zaga00** [comment]
Hello @amsnek,

yes, I think that in some cases `arg_path=url` should be used and in others `arg_path=path` - I don't remember exactly when but I think it depends on the protocol being used

**Comment by zaga00** [comment]
Hello @amsnek,

I think you should contact the haproxy mailing list (haproxy@formilux.org) for this problem because it is a problem in the implementation of SPOP - a change in the behavior of arguments related to a change in protocol.

**Comment by amsnek** [comment]
hmm ah I see. I thought it was mostly implementing "URI vs URL or PATH" but didnt consider that is something that has to be aviable in the SPOP (assuming that isnt currently).
https://docs.haproxy.org/2.6/configuration.html#1.2.1

**Comment by amsnek** [comment]
but Thanks a lot! This has given me some insights, also reminded me that H2 causes issues with my intentions to use the mirror module.

**Comment by amsnek** [comment]
I wonder if this works in the haproxy enterprise module 
https://www.haproxy.com/documentation/haproxy-enterprise/enterprise-modules/traffic-mirroring/

-> should face the same issue I assume

**Comment by zaga00** [comment]
For questions related to HAProxy Enterprise, please apply here: https://www.haproxy.com/contact-us

**Comment by amsnek** [comment]
yeah thanks, I will take a look into that
