### ISSUE TITLE
TCP Mirroring

### ISSUE THREAD

**Issue by sysolyakin** [haproxytech/spoa-mirror#36]
Hi!

I'm trying to find a way to mirror load to PostgreSQL instance, is it possible to mirror TCP traffic, not HTTP?

**Comment by zaga00** [comment]
Hello @sysolyakin,

I'm sorry but TCP traffic mirror is not possible, only HTTP/HTTPS.

**Comment by sysolyakin** [comment]
Okay, thanks

**Comment by clairvoyant** [comment]
@zaga00 


I really appreciate the time and effort you contribute to the community. 

Can you tell if there are any plans to add the TCP mirror in the future? 

Thanks!
